name: Snake Game Animation

on:
  schedule:
    - cron: "0 0 * * *" # Atualiza diariamente
  workflow_dispatch: # Permite iniciar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clonar o repositório
      - name: Clonar o repositório
        uses: actions/checkout@v2

      # Gerar a animação da cobrinha
      - name: Gerar a animação da cobrinha
        uses: Platane/snk@master
        with:
          github_user_name: SEU_USUARIO # Substitua pelo seu nome de usuário no GitHub

      # Fazer upload da animação gerada
      - name: Fazer upload da animação
        uses: actions/upload-artifact@v3
        with:
          name: github-contribution-grid-snake
          path: dist/github-contribution-grid-snake.svg
