name: Generate snake game

on:
  schedule: # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update data
    runs-on: ubuntu-latest
    steps:
      # Clonar o repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Gerar animação da cobra
      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: rafael-men
          outputs: dist/github-contribution-grid-snake.svg

      # Publicar a animação no branch 'output'
      - name: Publish to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.MY_SECRET_KEY }}

