name: Generate snake game

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Clonar o repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Snake Animation
      - name: Generate snake animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: rafael-men
          svg_out_path: dist/github-contribution-grid-snake2.svg
          snake_color: 'blue'

      # Publicar a animação no branch 'output'
      - name: Publish to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{secrets.MY_SECRET_KEY}}
